### ISSUE TITLE
h5py unable to read data 

### ISSUE THREAD

**Issue by kyungyunlee** [Chutlhu/dEchorate#35]
Hello! 
I am trying to read dataset (`dEchorate_rirs_gzip7.hdf5`) using the example notebook `notebooks/[Control] check RIRs in dEchorate_rirs.hdf5`.
Any idea why `rir_dset['rir']` shows the "unable to get group info" error ? 
I downloaded the most recent version (2.0) from zenodo. 
Thanks!

<img width="1006" alt="Screenshot 2022-12-17 at 10 54 36 AM" src="https://user-images.githubusercontent.com/19829532/208217948-369398be-b688-4e95-92c3-4781f6e9eb39.png">

**Comment by Chutlhu** [comment]
Thank you very much for the intereset in our dataset. I am currently looking at it.
Indeed, I looks there is an error on the uploaded version and I would like to apologize for it.
On my old python environment, it is working fine, but I am experiencing the same error with a new enviroment. I will soon upload the corrected version.

**Comment by Chutlhu** [comment]
Dear @kyungyunlee ,
I re-generated the whole dataset. Could you please try it from this link?
https://drive.google.com/drive/folders/1yGTh_BjnVNwDgBsn5mkuW3i4rJIgZwlS?usp=share_link
If there are no issues, I will re-upload everything.
I also updated the notebook in the `master` branch

**Comment by Chutlhu** [comment]
Thank you very much for your feedback.
I will soon update the zenodo link.
Please, do not hesitate to contact me here if you find any other problem.
