### ISSUE TITLE
dEchorate_rir_database.csv not found 

### ISSUE THREAD

**Issue by yasserboutaleb** [Chutlhu/dEchorate#36]
Hello,
The dEchorate_database.csv file used in the "[Control] check RIRs in dEchorate_rirs.hdf5.ipynb" notebook is not available in the provided zenodo dataset link.
Only the "dEchorate_database.csv" is available, which does not contain the rir column. 

Thank you for this great work!

**Comment by Chutlhu** [comment]
Sorry, the data has been moved temporarily here:
 https://drive.google.com/drive/folders/1yGTh_BjnVNwDgBsn5mkuW3i4rJIgZwlS

I will soon upload whole the files on Zenodo.
Do not hesitate to contact me for further explanation

**Comment by 793328114** [comment]
Hello, dEchorate_rir_database.csv still be not found in this link yet.


> Sorry, the data has been moved temporarily here: https://drive.google.com/drive/folders/1yGTh_BjnVNwDgBsn5mkuW3i4rJIgZwlS
> 
> I will soon upload whole the files on Zenodo. Do not hesitate to contact me for further explanation

**Comment by Chutlhu** [comment]
Thanks for your interest in our dataset.
I remember I modified the code. Please refer to the script. 
https://github.com/Chutlhu/dEchorate/blob/master/%5BControl%2CHDF5%5D%20check%20HDF5%20contents.ipynb

You can find all the files in the drive folder

**Comment by 793328114** [comment]
> 感谢您对我们的数据集感兴趣。我记得我修改了代码。请参考剧本。 https://github.com/Chutlhu/dEchorate/blob/master/%5BControl%2CHDF5%5D%20check%20HDF5%20contents.ipynb
> 
> 您可以在驱动器文件夹中找到所有文件

Thank you very much for your sharing and response。
