### ISSUE TITLE
HDF5 issue?

### ISSUE THREAD

**Issue by jmlemercier** [Chutlhu/dEchorate#37]
Hi there, 
Tried to download and open the RIR dataset with the HDF5 format. 
I used your notebook:

```
path_to_rirs_hdf = path_to_data / Path('dEchorate_rirs_gzip7.hdf5')
rir_dset = h5py.File(path_to_rirs_hdf, mode='r')

signals = list(rir_dset.keys())
print('Signals in this dataset:', signals)

rooms = list(rir_dset[signals[0]].keys())
print('Rooms in this dataset:', rooms)
```
and got the following hdf5 error: 

```
...
h5py/h5g.pyx in h5py.h5g.GroupID.get_num_objs()
RuntimeError: Unable to get group info (addr overflow, addr = 2536, size = 328, eoa = 2048)
```

I tried to update h5py but got the same issue, which I believe more or less means your file is corrupted or something?

Thanks in advance, would love to use this dataset.

**Comment by Chutlhu** [comment]
Dear @jmlemercier ,

Thank you very much for your interest.
Let me check this issues

**Comment by Chutlhu** [comment]
I regenerate the h5s
you can find it here:
https://drive.google.com/drive/folders/1yGTh_BjnVNwDgBsn5mkuW3i4rJIgZwlS?usp=sharing

Can you tell me if you experience the same errors?
If everything works, I will update the dataset on zenodo

Thank you very much

**Comment by Chutlhu** [comment]
Dear @jmlemercier ,

I am sorry to bother you, but did you have the occasion to check the data?
I would like to update the files and close the issue.

best regards

**Comment by jmlemercier** [comment]
Yes, works now! Thanks a lot
